//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceJourney.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Museums = new HashSet<Museum>();
        }
    
        public int AddressID { get; set; }
        public string City { get; set; }
        public string PostCode { get; set; }
        public string Country_Province_State { get; set; }
        public string Country { get; set; }
        public string OtherDetails { get; set; }
    
        public virtual ICollection<Museum> Museums { get; set; }
    }
}
