//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceJourney.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artefact
    {
        public Artefact()
        {
            this.Articles = new HashSet<Article>();
        }
    
        public int ArtefactID { get; set; }
        public Nullable<int> MuseumID { get; set; }
        public string ArtefactName { get; set; }
        public string ArtefactDescription { get; set; }
        public string Picture { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
    
        public virtual Museum Museum { get; set; }
        public virtual ICollection<Article> Articles { get; set; }
    }
}
