//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceJourney.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Museum
    {
        public Museum()
        {
            this.Artefacts = new HashSet<Artefact>();
            this.Articles = new HashSet<Article>();
        }
    
        public int MuseumID { get; set; }
        public Nullable<int> AddressID { get; set; }
        public Nullable<bool> Shop { get; set; }
        public Nullable<bool> Smoking { get; set; }
        public Nullable<int> AnnualVisitorCount { get; set; }
        public Nullable<System.DateTime> DateBuilt { get; set; }
        public Nullable<System.TimeSpan> OpeningHours { get; set; }
        public string MuseumName { get; set; }
        public string MuseumDescription { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Artefact> Artefacts { get; set; }
        public virtual ICollection<Article> Articles { get; set; }
    }
}
